/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "You realized yourself laying on cold ground. You are trying to open your eyes, but each time you try you get astonished\n            by unbearable headache. You decided to lay another couple minutes trying to remember who you are and whats happened": "你意识到自己躺在冰冷的地面上。你试图睁开眼睛，但每次尝试都会被无法忍受的头痛惊呆。你决定再躺几分钟，试着记住你是谁，发生了什么事",
    "About": "关于",
    "Actions": "行动",
    "After trying in vain for a while you tried to stand up. A piercing pain grips your body, but you feel like you definitely \n            can't just give up and die in cold. You need to find some place to warm up and take some sleep.": "在徒劳的尝试了一段时间后，你试图站起来。 一阵刺骨的疼痛笼罩着你的身体，但你觉得你绝对不能就这样放弃而死在寒冷中。 你需要找个地方暖和一下，睡一觉。",
    "Cooldown:": "冷却：",
    "Costs:": "费用：",
    "Energy": "能量",
    "Fortunately you found some bonfire not such far away from where you awaken. You put some sticks to flame, and it started\n            burning with new power. Well, now you can take some rest": "幸运的是，你在离你醒来的地方不远的地方发现了一些篝火。 你把一些棍子点燃，它开始\n以新的力量燃烧。 好了，现在你可以休息一下了",
    "Gold": "黄金",
    "Idlemancery": "巫术放置",
    "Learning": "学习",
    "Locked": "未解锁",
    "No actions available": "没有可用的操作",
    "OK": "好的",
    "Perform \"Rest\" action 3 times. Note, all actions have some cooldowns, you cant use them too frequently": "执行“休息”动作 3 次。 注意，所有动作都有一些冷却时间，你不能太频繁地使用它们",
    "Produce:": "生产：",
    "Requirements:": "要求：",
    "Rest": "休息",
    "Shop": "商店",
    "Story": "故事",
    "Take some rest to recover energy": "休息一下，恢复能量",
    "Time spent:": "花费的时间：",
    "What's happened": "发生了什么",
    "A place where you can store some todos - allow actions automation": "您可以存储一些待办事项的地方 - 允许操作自动化",
    "Collapse": "收起",
    "Day by day passed": "一天天过去",
    "Do some work to earn some gold": "做一些工作来赚取一些金子",
    "Each level will boost your actions effiency by decreasing cooldowns by 1%": "每级都会通过减少 1% 的冷却时间来提高你的行动效率",
    "Each level will boost your actions effiency by increasing their output by 1%": "每级都会通过增加 1% 的输出来提高你的行动效率",
    "Expand": "展开",
    "Gymnastics manual": "体操手册",
    "Increase your max gold": "增加你的最大金币",
    "Initiative": "能动性",
    "Manual": "手动",
    "Manual that learns you how to be more efficient at physical training": "教你如何提高体能训练效率的手册",
    "Manual that learns you how to be more efficient at work": "教你如何提高工作效率的手册",
    "Notebook": "笔记本",
    "Perform \"Work\" action 10 times. Take some rest between work to recover your energy": "执行“工作”动作 10 次。工作之间休息一下，恢复能量",
    "Perseverance": "毅力",
    "Pocket": "口袋",
    "Purchase notebook from shop tab": "从商店选项卡购买笔记本",
    "Set energy spent": "设置能量消耗",
    "Work at stable": "在马厩工作",
    "XP": "经验值",
    "You almost get used to this all routine. Work - rest at rancho - work again. Couple weeks later you finally\n            was able to store some trace amount of gold.": "你几乎已经习惯了这一切例行公事。工作 - 在牧场休息 - 再次工作。几周后，你终于\n 能够储存一些微量的黄金。",
    "You awaken feeling hungry. You decided to look around for some fruit trees in nearby forest. But, everything you found is \n            some old apple tree. You picked some fruits, just to take your mind off the hunger.": "你醒来感到饥饿。你决定在附近的森林里四处寻找一些果树。但是，你发现的一切都是\n 一些老苹果树。你摘了一些水果，只是为了让你的注意力从饥饿中解脱出来。",
    "You feel hungry": "你觉得饿了",
    "You started feeling headake. You began to remember something. Bright light, flames around you.\n        You screaming out from unbearable pain.": "你开始感到头晕目眩。你开始记起某事。明亮的光线，在你周围燃烧。\n 你因无法忍受的痛苦而尖叫。",
    "Automated": "自动化",
    "Book of basic magic": "基础魔法书",
    "Do some athletics to increase energy regeneration": "做一些田径运动来增加能量再生",
    "First memories": "最初的记忆",
    "No purchases available": "没有可用的购买",
    "Perform physical training 50 times, and get 5 levels in initiative and perseverance (learning tab)": "进行 50 次体能训练，获得 5 级的能动性和毅力（学习选项卡）",
    "Train stamina": "训练耐力",
    "Unlocks mana end some basic spells": "解锁法力结束一些基本法术",
    "You returned at rancho where you used to live and work last few weeks. You taken your seat at the floor and opened\n            your newly purchased book. At the very first page you saw nothing but just two words - MIGHTY, MAGIC": "你回到了你过去几周生活和工作的牧场。 你在地板上坐下并打开了\n你新买的书。 在第一页你什么都没有看到，只有两个词——强大，魔法",
    "Each level will boost your spells output by 1%": "每级使您的法术输出提高 1%",
    "Each level will decrease mana costs by 1%": "每升一级，法力消耗减少 1%",
    "Energy orb": "能量球",
    "Expand gold storage": "扩大黄金存储",
    "Expansion spell": "扩张法术",
    "Increase": "增加",
    "Magic": "魔法",
    "Mana": "法力",
    "Mana effiency": "法力效率",
    "Meditate": "冥想",
    "Spend whole day on receiving magic forces": "花一整天的时间接受魔法力量",
    "After whole day spent doing something weird and useless you felt completely disappointed.": "在花了一整天做一些奇怪而无用的事情之后，你感到完全失望。",
    "Another weekend, another walk through settlement. Nothing was unusual, until you hears cough behind you.": "另一个周末，另一个穿过定居点。没有什么异常，直到你听到身后的咳嗽声。",
    "Earn 40 gold": "获得 40 金币",
    "First meet with magic": "第一次遇见魔法",
    "Further chapter describe some strange techniques for meditation. Next chapters are just empty... \n        Seems useless, but OK - you spent\n        your money that you earned such difficultly. So, it worth a try now.": "下一章描述了一些奇怪的冥想技巧。下一章只是空的... \n 看起来没用，但是没关系 - 你花了\n 你赚的钱太难了。所以，现在值得一试。",
    "It appeared to be some old house at not such far away from the crossroads. You stepped in, opened the door.": "似乎是离十字路口不远的一座老房子。你走进去，打开门。",
    "It seems to have some... well, spells? You readen one of them, and than some strange chest appeared next to you.\n        After couple seconds it just dissapeared. Well, maybe you can find something really useful here?": "它似乎有一些……嗯，咒语？你读了其中一个，然后一个奇怪的箱子出现在你旁边。\n几秒钟后它就消失了。好吧，也许你可以在这里找到一些真正有用的东西？",
    "Mysterious men": "神秘人",
    "Perform expansion spell and energy orb 5 times": "施展扩张法术和能量球 5 次",
    "Perform meditation 5 times": "冥想5次",
    "Purchase book of magic": "购买魔法书",
    "Salesman quietly stepped towards one of shelves and takes some old dusty book": "推销员悄悄地走向其中一个书架，拿了一些尘土飞扬的旧书",
    "Salesman: -- Oh, man, you won't regret. Just trust me!": "推销员：——哦，伙计，你不会后悔的。相信我！",
    "So, you earned 40 gold as price tag required. You followed address that was pointed at piece of paper": "因此，您获得了 40 金币作为所需的价格标签。您关注了指向一张纸的地址",
    "Some items in shop seems like not have obvious use, but you will need to purchase them to unlock new game content": "商店中的某些物品似乎没有明显用途，但您需要购买它们才能解锁新的游戏内容",
    "Spells are pretty powerful way to improve yourself, but they consume a lot mana. You can visit learning pageto improve their efficiency": "咒语是提高自己的强大方法，但会消耗大量法力。您可以访问学习页面以提高他们的效率",
    "Strange exercises": "奇怪的练习",
    "Strange man: -- Here it is. Give him your gold and take a book": "怪人：——来了。给他你的金子，拿一本书",
    "Strange man: -- Nevermind. Just take this.": "怪人：——没关系。就拿这个吧。",
    "Strange man: -- Oh, here you are! Okey, we need to give some good start to our newcomer.": "陌生人：——哦，你来了！好吧，我们需要给我们的新人一个好的开始。",
    "Strange man: -- You will get answer to your question soon, once you will be ready. For now you can call me your destiny.": "奇怪的人：——一旦你准备好了，你很快就会得到你的问题的答案。现在你可以称我为你的命运。",
    "Strange purchase": "奇怪的购买",
    "Well, you are doing well. You found job, you found place to leave. Rancho owner trust you, you keep earning more \n            and more. But feeling that you worth more keep teasing you.": "好吧，你做得很好。你找到了工作，你找到了离开的地方。牧场主信任您，您会不断赚取更多\n 和更多。但感觉你更有价值，不断取笑你。",
    "You can check shop anytime for any useful stuff that might help you to earn money. Also, keep do physical training. You'll need a lot energy in future": "您可以随时查看商店是否有任何可以帮助您赚钱的有用物品。另外，继续进行体能训练。未来你需要很多能量",
    "You opened book again, and suddenly circle on the first page started glowing. You tried to touch it,\n        and you felt some strange heat. You started turning pages, and OMG! You realized second chapter is no\n        longer empty!": "你再次翻开书，突然第一页上的圆圈开始发光。你试着去触摸它，\n你感觉到了一些奇怪的热度。你开始翻页了，天哪！你意识到第二章不再是空的了！",
    "You returned to your rancho. Ok, it's not yours :)": "你回到了你的牧场。好吧，这不是你的:)",
    "You taken your seat at the carpet on the ground, as usual, and opened book. At the first page there was nothing\n        but some strange black circle.": "你像往常一样坐在地上的地毯上，打开书本。在第一页，除了一些奇怪的黑色圆圈之外什么都没有。",
    "You turned around, and saw whole variety of strange things (like teeth necklaces, weird clothes other trinkets).\n        Finally, you saw the same strange man you talked before, speaking with another one, who looks like salesman": "你转身，看到了各种各样的奇怪的东西（比如牙齿项链，奇怪的衣服其他小饰品）。\n最后，你看到了你之前说话的那个奇怪的人，和另一个看起来像推销员的人说话",
    "You turned around... And, OMG! His cloak, his eyes... it is indeed the same man who you saw couple weeks ago \n        in the mirror. You asked the same question: \"Who are you?\"": "你转过身来……而且，天哪！他的斗篷，他的眼睛……确实是你几周前在镜子里看到的那个人。你问了同样的问题：“你是谁？”",
    "You: -- Newcomer? Start of what?": "你：—— 新人？什么开始？",
    "You: -- What in the name of God I am paying for?": "你：—— 我为上帝的名义付出了什么？",
    "You: -- What??? What are you talking about?": "你：—— 什么？？？你在说什么？",
    "Book of meditation": "冥想之书",
    "Copy to clipboard": "复制到剪贴板",
    "Download as file": "下载为文件",
    "Export game": "导出游戏存档",
    "Import game": "导入游戏存档",
    "Magic stamp": "魔法邮票",
    "Perform Energy Orb spell 10 times, physical training 125 times. Purchase magic stamp.": "施展能量珠法术 10 次，体能训练 125 次。 购买魔法印章。",
    "Provides ability to store more magic powers. +10 max mana, +25% spells power": "提供储存更多魔力的能力。 +10 最大法力，+25% 法术强度",
    "Purchase book full of usefull meditation techniques. Meditation takes twice as much energy but provides 2x mana.": "购买一本充满有用的冥想技巧的书。 冥想消耗两倍的能量，但提供 2 倍的法力。",
    "Salesman: -- Ok, I can learn you something. Give me your magic stamp.": "推销员：——好的，我可以教你一些东西。 给我你的魔法印章。",
    "Salesman: -- You came for more, right?": "推销员：——你来是为了更多，对吧？",
    "Slightly bored": "有点无聊",
    "You left the shop with strong feeling of disappointment. You have to work a lot and hard to purchase another\n        trinket! But, you must! You have to do this! Maybe...": "你带着强烈的失望情绪离开了商店。 您必须付出很多努力才能购买另一个\n 饰品！ 但是，你必须！ 你必须这样做！ 也许...",
    "You: -- I feel I am missing something. There should be more use for magic.": "你：——我觉得我错过了什么。 魔法应该有更多的用途。",
    "You: Silently starring at salesman with doubt": "你：默默盯着推销员疑惑",
    "And again, you should return to your rancho full of frustration.": "再说一次，你应该满怀沮丧地回到你的牧场。",
    "Another try": "再试一次",
    "Magic lessons": "魔法课",
    "Purchase time-management book that learn you to keep 2 actions auto-running": "购买时间管理书，让你学会保持 2 个动作自动运行",
    "Salesman: -- I want to show you how to extend your magic knowledge.": "推销员：——我想告诉你如何扩张你的魔法知识。",
    "Salesman: -- Well, now I can show you something": "推销员：——嗯，现在我可以给你看点东西",
    "Salesman: -- You are not ready yet.": "推销员：——你还没准备好。",
    "Take courses of magic": "参加魔术课程",
    "Take magic lessons 5 times.": "上魔法课5次。",
    "Time-management": "时间管理",
    "You may want to purchase Time-management book in shop to make progress more idle": "您可能想在商店购买时间管理书以使进度更加空闲",
    "You: -- But what about new spells?!": "你：——但是新法术呢？！",
    "You: -- Show me what?": "你：——给我看什么？",
    "Bargaging": "讨价还价",
    "Increase place for gold by 200": "增加黄金存储上限200",
    "Learn basics of bargaging - improve your gold earned by 2 per work action": "学习讨价还价的基础知识 - 每个工作动作将您的黄金提高 2",
    "Purchase a shovel to make your work even more efficient. Work takes 2 energy more but provides 2 more gold.": "购买一把铲子，让您的工作更有效率。 工作多消耗 2 能量，但提供 2 更多金币。",
    "Shovel": "铲子",
    "Stash": "藏匿",
    "Basic summoning": "基础召唤",
    "Purchase basic sumonning manual": "购买基础召唤手册",
    "Mana orb": "法术球",
    "Purchase orb that improves your meditation. Meditation takes 10 more energy but provide 1 more mana": "购买可以改善您的冥想的球体。 冥想多消耗 10 点能量，但提供多 1 点法力",
    "Have 500 gold. Purchase book of summoning": "拥有500金币。 购买召唤之书",
    "Now you exiting shop with full of enthusiasm. You know you should work hard, but you almost sure - that worth it!": "现在你满怀热情地离开商店。 你知道你应该努力工作，但你几乎可以肯定——这是值得的！",
    "Salesman silently token another dusty book": "推销员默默地令牌另一本尘土飞扬的书",
    "Salesman: -- Ok. Now I guess you ready.": "售货员：——好的。 现在我猜你准备好了。",
    "Salesman: -- Ready for true knowledge": "推销员：——为真正的知识做好准备",
    "Salesman: -- Wait, it's not for free. True knowledge should be deserved.": "推销员：——等等，这不是免费的。 真正的知识应该是值得的。",
    "True knowledge": "真正的知识",
    "You: -- Oh, finally! Thanks!": "你：——哦，终于！ 谢谢！",
    "You: -- Ready for what?": "你：——准备好做什么了吗？",
    "Amount per click:": "每次点击数量：",
    "Consume:": "消耗：",
    "Cost:": "成本：",
    "Creatures": "生物",
    "Dark Researcher": "黑暗研究员",
    "energy per second. When you run out of energy your creatures will disappear. Make sure you have enough energy production before spending precious souls.": "每秒能量。当你耗尽能量时，你的生物就会消失。在花费宝贵的灵魂之前，请确保您有足够的能量生产。",
    "Every creature consumes": "每个生物都会消耗",
    "Fighter": "战士",
    "First assistants": "第一助理",
    "Free workers:": "空闲工人：",
    "Have 5 supporters and 1 miner": "有5个支持者和1个矿工",
    "Herbalism": "草药学",
    "Mage": "法师",
    "max energy at least": "至少最大能量",
    "Miner": "矿工",
    "Navigate to creatures tab. Create at least one creature": "导航到生物选项卡。创造至少一个生物",
    "New Life": "新生活",
    "Not alone any longer": "不再孤单",
    "Purchase herbalism book to take advantages of flasks": "购买草药书以利用烧瓶",
    "Purchase knowledge of better soul harvesting": "购买更好的灵魂收割知识",
    "Purchase summoning jobs knowledge book to increase job effiency. +10% creature productions": "购买召唤职业知识书，提高工作效率。 +10% 生物产量",
    "Refine soul": "提炼灵魂",
    "Refine soul 4 times": "精炼灵魂4次",
    "Refines some mana to soul": "为灵魂提炼一些法力值",
    "Requires": "需要",
    "Salesman mumbled something quietly something. Wall behind him disappeared, and you saw stairs.": "推销员小声嘟囔着什么。他身后的墙消失了，你看到了楼梯。",
    "Salesman: -- Follow me.": "推销员：——跟我来。",
    "Salesman: -- Here is your new apartment": "推销员：——这是你的新公寓",
    "Salesman: -- Ok. So, from now you are part of our dark mages community.": "售货员：——好的。所以，从现在开始，你就是我们黑暗法师社区的一员。",
    "Salesman: -- Yes you! You can't keep living at rancho with other people. Let me show your new appartments.": "推销员：——是你！你不能继续和其他人一起住在牧场。让我展示你的新公寓。",
    "Soul harvester": "灵魂收割机",
    "Souls": "灵魂",
    "Summon (x": "召唤（x",
    "Summoning Jobs": "召唤工作",
    "   ": "支持者",
    "Total creatures:": "生物总数：",
    "Well, what they can do? You started turning pages in book. At last, you found it! You found a use for them! Now they can \n            do some jobs for you!": "那么，他们能做什么？你开始翻书。终于，你找到了！你找到了它们的用途！现在他们可以\n为你做一些工作！",
    "You: -- Apartment? Okey.": "你：——公寓？好的。",
    "You: -- Apartments? Well!": "你：——公寓？出色地！",
    "You: -- Me? Mage? Mages community?": "你我？法师？法师社区？",
    "Collect herbs": "收集草药",
    "Collect herbs as raw material for flasks": "收集草药作为烧瓶的原料",
    "Flasks": "烧瓶",
    "Herbalists stash": "草药师藏匿",
    "Herbs": "草药",
    "Make flasks": "制作烧瓶",
    "Make some flasks to improve creatures efficiency": "制作一些烧瓶以提高生物效率",
    "Purchase special container for herbs. +20 max herbs.": "购买草药的特殊容器。 +20 最大草药。",
    "Supporter": "支持者",
    "Advanced magic": "高级魔法",
    "Another day passed, your minions working hard together with you. You was just about to perform usual for you\n            soul harvest ritual, when door cracked, and you saw familiar silhouette.": "又一天过去了，你的手下和你一起努力工作。你刚要为你进行平常的灵魂收割仪式，门就裂开了，你看到了熟悉的身影。",
    "Breaking bad": "绝命毒师",
    "Each next flask provides less bonus than previous one. You can see bonus hovering over over them": "每个下一个烧瓶提供的奖励都比前一个少。您可以看到奖励悬停在它们上方",
    "Have at least 10 flasks": "至少有 10 个烧瓶",
    "Have at least 51 creature": "拥有至少 51 个生物",
    "Keep going for more": "继续前进",
    "Next morning you stepped into shop and saw two books that mage might have spoken about.": "第二天早上，你走进商店，看到了两本法师可能说过的书。",
    "Now you know the basics": "现在你知道了基础知识",
    "Purchase book that further increase your magic power by 50%": "购买可以进一步增加你的魔力50%的书",
    "Purchase herbalism and better summoning books": "购买草药学和更好的召唤书",
    "Strange man in cloak: -- Hey there. I see you doing well, yeah? Must be somewhat proud of yourself?": "披着斗篷的怪人：——嘿。我看你做得很好，是吗？一定有点为自己感到骄傲吗？",
    "Strange man in cloak: -- You shouldn't be so proud. It's only the very basics of what you actually capable if.\n        You should keep getting new knowledge.": "斗篷怪人：——你不应该这么骄傲。这只是你实际能力的基础知识。\n 你应该不断获得新知识。",
    "Than mage disappeared, left you confused. You left sitting for a while just thinking about what the hell did happened\n         just now.": "比法师消失了，让你一头雾水。你坐了一会儿，只是想着刚才到底发生了什么\n。",
    "You looked at book that you have almost read: -- What kind of knowledge? Where can I take it?": "您看了几乎读过的书： -- 什么样的知识？我可以把它带到哪里？",
    "You spent enough time boiling flasks. Seems like you still need more. More resources, more creatures, more might...": "你花了足够的时间煮烧瓶。看来你还需要更多。更多的资源，更多的生物，更多的力量……",
    "You: -- Smiled slightly": "你：——微微一笑",
    "Advanced soul harvester": "高级灵魂收割机",
    "Purchase book that further increase your souls gain": "购买进一步增加你的灵魂增益的书",
    "Increase your": "提高你的",
    "Again in forest": "又在森林里",
    "Banners": "旗帜",
    "Blue banner": "蓝色旗帜",
    "By prestieging you will loose all your skills, spells, actions and shop items. But, you will gain some amount of tier 1 banners you selected. The amount depends on currently summoned creatures you have.": "通过声望，你将失去所有的技能、法术、动作和商店物品。但是，您将获得一定数量的您选择的 1 级旗帜。数量取决于您当前拥有的召唤生物。",
    "Dulequar: -- Please, calm down my child.": "Dulequar：——请让我的孩子冷静下来。",
    "Green banner": "绿色旗帜",
    "Have at least 1 of yellow, orange, blue and green banners.": "至少有 1 个黄色、橙色、蓝色和绿色旗帜。",
    "Improves your mana creatures production": "提高你的法术力生物产量",
    "Improves your miner creatures production": "提高你的矿工生物产量",
    "Improves your personal actions and spells production": "改善你的个人行为和法术生产",
    "Improves your support creatures production": "提高你的支持生物产量",
    "Navigate to banners tab and click prestige under any of them.": "导航到旗帜选项卡并单击其中任何一个下的声望。",
    "Orange banner": "橙色旗帜",
    "Shining light": "闪耀的光芒",
    "So weird, so unfairly!": "好诡异，好不公平！",
    "Tier": "层级",
    "Wizard: -- My name is Dulequar.": "巫师：——我叫杜勒夸。",
    "X1.28 提升": "X1.28 提升",
    "Yellow banner": "黄色旗帜",
    "You almost paralyzed but you have to reach one of mirrors. YOU SHOULD!": "你几乎瘫痪了，但你必须够到一面镜子。你应该！",
    "You realized yourself again laying in forest. All your money, all your powers... They just gone.": "你意识到自己再次躺在森林里。你所有的钱，你所有的权力......他们就这样消失了。",
    "You sit down at one of stumps next to bonfire thinking about all your efforts where vain, when you saw \n        again familiar mirror occurred with familiar man": "你坐在篝火旁的一个树桩上想着你所有的努力都徒劳无功，当你再次看到\n熟悉的镜子出现在熟悉的男人身上时",
    "You summoning more and more creatures. Maintaining them all becomes harder and harder. You almost can't eat nor sleep.\n        Never felt so exhausted... But you feel like you should keep pushing.": "你召唤越来越多的生物。维护它们变得越来越难。你几乎不能吃也不能睡。\n从未感到如此疲惫......但你觉得你应该继续努力。",
    "You will have to re-gain all your lost resources and skills, but you will do it much faster now. Also, you unlocked new way to improve your self - a dark research.": "你将不得不重新获得所有失去的资源和技能，但现在你会做得更快。此外，您解锁了改善自我的新方法 - 一项黑暗的研究。",
    "You: -- I trusted you. And now I lost everything I had again!": "你：——我信任你。而现在我又失去了我所拥有的一切！",
    "You: -- In the name of God, who are you?! Why can't you just leave me alone? Why you are chasing me?": "你：——以上帝的名义，你是谁？！你为什么不能让我一个人呆着？你为什么追我？",
    "You: -- Ok! I can't even remember mine name. I can't remember anything since I realized myself here in forest\n         some time ago!": "你还好吗！我什至不记得我的名字。自从我意识到自己在森林里\n前段时间以来，我什么都不记得了！",
    "Purchase summoning effiency book to decrease energy consumed by creatures by 0.5": "购买召唤效率书减少生物消耗的能量0.5",
    "Summoning Effiency": "召唤效率",
    "Again rainy cold forest. The same mirror appeared, and you see again familiar man into it.": "又是阴雨冷林。同样的镜子出现了，你再次看到熟悉的人进入它。",
    "Banners Masterity": "旗帜精通",
    "Convert (+": "转换 (+",
    "Dulequar gave you another old dusty book. You read two words written on it in big letters.": "Dulequar 给了你另一本尘土飞扬的旧书。你读到上面用大字写的两个字。",
    "Dulequar: -- No worries, that's ok. I came to give you something.": "Dulequar：——不用担心，没关系。我是来给你东西的。",
    "Dulequar: -- Well, I should admit - you are doing pretty well.": "Dulequar：——嗯，我应该承认——你做得很好。",
    "Dulequar: -- Yes, it's impossible to achieve new powers without new sciences. And remember to use your \n        knowledge wisely!": "Dulequar：——是的，没有新的科学就不可能获得新的力量。并记住明智地使用您的 \n 知识！",
    "Each level decrease souls costs of summoning exponenta by 5%": "每升一级，召唤指数的灵魂消耗减少 5%",
    "Each level increase your actions effiency by 20%": "每级提高你的行动效率20%",
    "Each level increase your spells effiency by 25%": "每升一级，你的法术效率提高 25%",
    "Each level makes your learning speed 50% faster": "每个级别让你的学习速度快50%",
    "Energizer": "劲量",
    "Fighting Masterity": "战斗精通",
    "Have at least 3 levels of Self Development and Soul Eater researches.": "拥有至少 3 个级别的自我发展和噬魂者研究。",
    "Improves your banners effect exponenta over amount by 0.01": "将您的旗帜效果指数提高 0.01",
    "Improves your dark researchers effiency": "提高你的黑暗研究人员的效率",
    "Improves your soul gain from all sources by 10%": "提高你从所有来源获得的灵魂 10%",
    "Necromancery": "死灵术",
    "New powers": "新权力",
    "Prestige (+": "声望 (+",
    "Research": "研究",
    "Self Development": "自我发展",
    "Soul Eater": "噬魂者",
    "Spells master": "法术大师",
    "Start with 0.5 more basic energy regen and 5 more energy capacity": "开始时增加 0.5 点基础能量恢复和 5 点能量容量",
    "Tireless": "不知疲倦",
    "Unlocks fighting. Each level increase your creatures HP and attack by 25%": "解锁战斗。每级增加你的生物生命值和攻击力25%",
    "Violet banner": "紫罗兰色旗帜",
    "You can hire researchers to generate research points and purchase some new upgrades for it": "您可以聘请研究人员来生成研究点并为其购买一些新的升级",
    "You: -- But still I am here in the same forest with naked back.": "你：——但我仍然在同一个森林里，光着背。",
    "You: -- Dark research? What is it?": "你：——黑暗研究？它是什么？",
    "At this point story itself ends for now. Still working on more stuff.": "至此，故事本身就结束了。 仍在研究更多的东西。",
    "Battle": "战斗",
    "Enter fight": "进入战斗",
    "Even more": "甚至更多",
    "Have at least 3 levels of Necromancery and Spellmaster.": "拥有至少 3 级死灵法师和法术大师。",
    "HP:": "生命值：",
    "Map [": "地图 [",
    "None": "无",
    "Progress:": "进度：",
    "Toggle auto-next map": "切换自动下一张地图",
    "Turn on": "打开",
    "You definitely much and much stronger. Each next research/run will go easier and easier. Keep unlock new researches.": "你肯定要强大得多。 每次下一次研究/运行都会越来越容易。 不断解锁新的研究。",
    "Join Discord": "加入 Discord",
    "Show purchased": "显示已购买",
    "Hide purchased": "隐藏已购买",
    "Advanced herbalism": "高级草药学",
    "Advanced soul harvester II": "高级灵魂收割机 II",
    "Enpower all your spells by 50%": "强化你所有的法术 50%",
    "Purchase book full of knowledge about herbs. +100% herbs gain": "购买一本充满草药知识的书+100%草药增益",
    "Manual of appretience": "感知手册",
    "(Sold)": "（已售出）",
    "Building": "建筑",
    "Go to map level (max -": "进入地图等级（最大 -",
    "Territory": "领土",
    "Turn off": "关掉",
    "Unlocks building. Each level increase builder effiency by 20%": "解锁建筑。 每级提高建造者效率20%",
    "Wood": "木头",
    "Stone": "石头",
    "Academy": "学院",
    "Build": "建造",
    "Builder": "建筑工",
    "Each level allows to store some amount of building resources": "每个级别都允许存储一定数量的建筑资源",
    "Each level increase gold maximum and gold income by 10%": "每级增加金币上限和金币收入 10%",
    "Each level increase research production by 20%": "每级增加 20% 的研究产出",
    "Each level increase souls production by 10%": "每级增加 10% 的灵魂产量",
    "Enemy Mock": "敌人模拟",
    "Exit fight": "退出战斗",
    "Graveyard": "墓地",
    "Palace": "宫殿",
    "Stonecutter": "切石机",
    "Time:": "时间：",
    "Warehouse": "仓库",
    "Warriors": "勇士",
    "Woodcutter": "伐木工",
    "Some of researches can be unlocked by 2-3 levels of previous ones.": "一些研究可以通过之前的2-3级解锁。",
    "A sword pierced your body. You felt over. Everything darkened. That's the end...": "一剑刺穿了你的身体。你感觉结束了。一切都变暗了。就这样结束了……",
    "After returning back to your basement, Dulequar gave you another scroll. Well, you feel you know what to do!": "回到你的地下室后，杜勒夸又给了你一个卷轴。好吧，你觉得你知道该怎么做了！",
    "Another frosty morning. As usual, you walked through the forest back to settlement, enjoying the fresh inter air and shining sun.\n        Suddenly, you recognized the same old mirror with familiar face into it.": "又是一个寒冷的早晨。像往常一样，你穿过森林回到定居点，享受着新鲜的空气和灿烂的阳光。\n 突然，你认出了那面老镜子，里面有一张熟悉的面孔。",
    "Another squad of weird skeletons crashed like toys.": "又一队怪异的骷髅像玩具一样轰然倒塌。",
    "At this point story ends for now. To be developed in future...": "至此，故事暂时告一段落。未来有待开发...",
    "Dulequar: - But that's tre truth. Anyway, you should start getting prepared to our Holy war. We can't afford defeat. Take this.": "Dulequar： - 但这是真的。无论如何，你应该开始为我们的圣战做好准备。我们承受不起失败。拿着这个。",
    "Dulequar: - Follow me. I have to show you something.": "Dulequar： - 跟我来。我得给你看点东西。",
    "Dulequar: - Not whole city, but whole world actually. He tries to turn all of us in his slaves. Kill us and enslave our souls.": "Dulequar: - 不是整个城市，而是整个世界。他试图把我们所有人都变成他的奴隶。杀死我们，奴役我们的灵魂。",
    "Dulequar: - Once upon a time you will have even better.": "Dulequar： - 曾几何时，你会拥有更好的。",
    "Dulequar: - Overthere!": "Dulequar： - 那边！",
    "Dulequar: - Trust me, that's not sweet at all. Give me your hand": "Dulequar： - 相信我，这根本不甜。把你的手给我",
    "Dulequar: - Watch your back!!!": "Dulequar: - 小心你的背影！！！",
    "Dulequar: - Well, it's my tiny estate.": "Dulequar： - 嗯，这是我的小庄园。",
    "Dulequar: - Well, that's Azragard and his minions.": "Dulequar： - 嗯，那是阿兹拉加德和他的手下。",
    "Dulequar: - Well, to be honest, I didn't expected you to survive. But I had to show you this.": "Dulequar： - 好吧，老实说，我没想到你能活下来。但我必须给你看这个。",
    "Dulequar: - Well, you don't look like the weak and confused man I first saw at the ranch. I feel you are ready for \n        the trial that your destiny prepared for you.": "Dulequar： - 嗯，你看起来不像我第一次在牧场看到的那个虚弱而困惑的人。我觉得你已经为你的命运为你准备的考验做好了准备。",
    "Research building.": "研究建造。",
    "Research fighting. Clear out second zone at least once.": "研究战斗。至少清除第二个区域一次。",
    "Some of them were carrying some goods, some of them just walking enjoying great looks": "他们中的一些人带着一些货物，一些人只是走路享受美丽的景色",
    "The Holy War": "圣战",
    "You recognized your self laying in the forest next to the mirror": "你认出了自己躺在镜子旁边的森林里",
    "You see a horde of living skeletons approaching you. Dulequar spelled something similar to summoning spell. A mighty \n        ogre of tremendous size in shinning armor appeared. He raised his mace and smashed skeletons approaching you.": "你看到一大群活生生的骷髅向你靠近。 Dulequar 拼出了类似于召唤咒语的东西。一个身穿闪亮盔甲、体型巨大的强大食人魔出现了。他举起狼牙棒，砸碎靠近你的骷髅。",
    "You started thinkin: -No, it can't be the end. I can not just die!": "你开始想：-不，这不可能是结束。我不能就这么死！",
    "You was about to portal back to you room in basement when you felt someones hand on your shoulder.": "当你感觉有人把手放在你的肩膀上时，你正要传送回地下室的房间。",
    "You: - Good job, guys!": "你： - 干得好，伙计们！",
    "You: - Let's hope I won't die this time": "你：-希望这次我不会死",
    "You: - Me?": "你我？",
    "You: - Sounds like great plot of the fantasy film.": "你： - 听起来像是奇幻电影的精彩情节。",
    "You: - Well, another adventure? Sounds sweet!": "你： - 好吧，又一次冒险？听起来很甜！",
    "You: - What just happened? Where I was? Who are these armies of living skeletons?": "你： - 刚刚发生了什么？我在哪里？这些活着的骷髅军队是谁？",
    "You: - Who is Azragard? Why would he try to demolish whole city?": "你： - 阿兹拉加德是谁？他为什么要试图拆毁整个城市？",
    "You: So, where we are?": "你：那么，我们在哪里？",
    "You: Tiny estate?! It looks like something... It's amazing!": "你：小庄园？！它看起来像什么……太神奇了！",
    "Your warrior creatures glanced at you blankly. You almost believed they actually understand when you talking to them.": "你的战士生物茫然地看着你。当你和他们交谈时，你几乎相信他们真的理解了。",
    "A book for storing notes and goals. Adds 1 automation slot.": "用于存储笔记和目标的书。添加 1 个自动化插槽。",
    "A manual that provides some techniques for general exercising. Train stamina is now twice as efficient.": "提供一些一般练习技巧的手册。训练耐力现在效率提高一倍。",
    "A manual that provides some techniques on effective laboring. Work at Stable action is now twice as costly but twice as effective also.": "提供一些有效劳动技巧的手册。 在马厩工作 行动现在的成本是原来的两倍，但效果也是两倍。",
    "A small coin bag that increases your maximum gold by 20.": "一个小硬币袋，可将您的最大金币增加 20。",
    "All": "全部",
    "Allows you building": "允许您构建",
    "Bargaining": "讨价还价",
    "Basic": "基础",
    "Bones masterity": "骨骼精通",
    "Born to bring Death": "为带来死亡而生",
    "Brown banner": "棕色横幅",
    "By prestiging you will lose all your skills, spells, actions and shop items. But, you will gain some amount of tier 1 banners you selected. The amount depends on currently summoned creatures you have.": "通过声望，您将失去所有技能、咒语、动作和商店物品。但是，您将获得一定数量的您选择的 1 级横幅。数量取决于您当前拥有的召唤生物。",
    "By setting effort you are setting amount of energy you will spend per second to learn skill. Maximum effort per skill is 50% of your": "通过设置努力，您可以设置每秒学习技能所花费的能量。每个技能的最大努力是你的 50%",
    "By setting effort you are setting amount of energy you will spend per second to learn skill. Maximum effort per skill is 50% of your 最大能量": "通过设置努力，您可以设置每秒学习技能所花费的能量。每个技能的最大努力是你最大能量的 50%",
    "City Planning": "城市规划",
    "Coin Bag": "零钱袋",
    "Combat": "战斗",
    "Combat Logistics": "战斗后勤",
    "Combat Tactics": "作战战术",
    "Convert 10%(+": "转换 10%(+",
    "Dark Experiments": "黑暗实验",
    "Each level decrease building gold and territory requirement by 10%": "每级减少 10% 的建筑金币和领土要求",
    "Each level decrease exponent base in souls costs of summoning formula by 5%. Max out to unlock new research.": "每升一级，召唤公式的灵魂成本指数基础降低 5%。最大限度地解锁新的研究。",
    "Each level increase your actions effiency by 20%. After level 10 unlock new powerful research.": "每个级别都会将您的行动效率提高 20%。 10 级后解锁新的强大研究。",
    "Each level increase your spells effiency by 25%. After levels 5 and 10 unlock new researches": "每升一级，你的法术效率提高 25%。 5 级和 10 级后解锁新的研究",
    "Each level will decrease mana costs of spells by 1%": "每升一级，法术的法力消耗降低 1%",
    "Economy": "经济",
    "Fights and captures new territories for you": "为你战斗并占领新的领土",
    "Fights are 5% faster. After level 3 unlock new research.": "战斗速度提高 5%。 3级后解锁新的研究。",
    "Further increase your magic power by 50%": "进一步增加你的魔力50%",
    "Gathers energy": "聚集能量",
    "Gathers gold": "收集黄金",
    "Gathers mana": "收集法力",
    "Gathers research points (RP)": "收集研究点 (RP)",
    "Gymnastic's manual": "体操手册",
    "Hide researched": "隐藏已研究",
    "Hide unavailable": "隐藏不可用",
    "Improve your dark research output by 20%. Also improve academy effect by 5%": "将你的黑暗研究产出提高 20%。同时提升学院效果5%",
    "Improves builders and building resources gatherers effiency": "提高建设者和建筑资源收集者的效率",
    "Increase your training efficiency by 100%": "将您的训练效率提高 100%",
    "Labor Manual": "劳动手册",
    "Learn how to manage 2 more tasks simultaneously. More than 2 automations making you less efficient.": "了解如何同时管理另外 2 个任务。超过 2 种自动化使您的效率降低。",
    "Multi-tasking": "多任务处理",
    "Perform Energy Orb spell 10 times, physical training 75 times. Purchase magic stamp.": "施展能量珠法术 10 次，体能训练 75 次。购买魔法印章。",
    "Perform physical training 30 times, and get 5 levels in initiative and perseverance (learning tab)": "进行 30 次体能训练，获得 5 个级别的主动性和毅力（学习选项卡）",
    "Purchase all": "全部购买",
    "Purchase book that decrease souls consumed by creatures by 75%": "购买减少被生物消耗的灵魂 75% 的书",
    "Set all to 0": "全部设置为 0",
    "Show researched": "显示已研究",
    "Show unavailable": "显示不可用",
    "Start your runs with 5 supporters, 3 miners, 1 mana gatherer and summoning book purchased": "购买 5 个支持者、3 个矿工、1 个法力收集器和召唤书，开始你的奔跑",
    "Training equipment": "培训设备",
    "Unlocks building. Each level increase builder efficiency by 20%. Level 5 unlocks new banner.": "解锁建筑。每个级别都会提高 20% 的建造效率。 5 级解锁新横幅。",
    "Unlocks fighting. Each level increase your creatures HP and attack by 25%. Levels 2 and 6 unlock new researches": "解锁战斗。每升一级，你的生物生命值和攻击力提高 25%。 2 级和 6 级解锁新研究",
    "Unlocks hiring sergeant. Each level increase sergeant bonus by 10%": "解锁雇佣军士。每级增加10%的中士奖励",
    "Purchase book that decrease souls consumed by creatures by another 75%": "购买将生物消耗的灵魂再减少 75% 的书",
    "Advanced Automation": "高级自动化",
    "Banking": "银行业",
    "Each level further decrease costs of summoning.": "每个级别都会进一步降低召唤成本。",
    "Each level increase max building materials storage by 25%.": "每个级别都会增加 25% 的最大建筑材料存储量。",
    "Each level increase max gold storage by 20%. Unlock building banks.": "每个级别都会增加 20% 的最大黄金存储量。 解锁建筑银行。",
    "Each level increase souls production and fight rewards by 20%": "每级增加20%的灵魂产出和战斗奖励",
    "Each level increase your creatures block by 2": "每升一级，你的生物格挡增加 2",
    "Increase building materials storage": "增加建材储存量",
    "Increase fighting loot by 25%.": "战斗战利品增加 25%。",
    "Logistics": "后勤",
    "Looting": "掠夺",
    "Never": "从不",
    "Packing spell": "包装拼写",
    "Provides raw material for building. Although it seems pretty cheap material, for some reason it's pretty hard to learn your creatures to cut wood": "为建筑提供原材料。 虽然它看起来很便宜，但由于某种原因，很难让你的生物学会砍木头",
    "Provides stone for building.": "为建筑提供石头。",
    "Start with 50 more maximum gold and more passive gold income (+31.62). After level 10 unlock new research": "从 50 更多的最大金币和更多的被动金币收入开始（+31.62）。 10级后解锁新研究",
    "Summoning Mastery": "召唤精通",
    "Training Camp": "训练营",
    "Unlocks auto-purchase for items you have ever purchased over previous resets.": "解锁您在以前重置时购买过的物品的自动购买。",
    "Aggressive": "激进",
    "Authoritative": "权威",
    "Choose your temper": "选择你的性格",
    "Decrease creatures cost by 20%": "降低生物消耗 20%",
    "Energetic": "精力充沛",
    "Increase fighters stats by 20%. Battles are 10% faster": "战士属性增加 20%。 战斗速度加快 10%",
    "Increase maximum energy by 20 + 25%. Increase ener… by 20%. Start with 10 training stamina performed": "最大能量增加 20 + 25%。 增加能量…… 20%。 从 10 次耐力训练开始",
    "Increase maximum gold by 50 + 25%. Increase gold income by 20%. Start with bargaining purchased": "将最大金币提高 50 + 25%。 增加20%的黄金收入。 从讨价还价开始购买",
    "Increase maximum mana by 10 + 25%. Increase mana income by 20%.": "最大法力值提高 10 + 25%。 法力收入增加 20%。",
    "Increase research income by 20%": "研究收入增加 20%",
    "Saving": "保存",
    "Select": "选择",
    "Spiritual": "精神",
    "Wise": "明智",
    "You lost 1 creatures due to lack of energy.": "由于缺乏能量，你失去了 1 个生物。",
    "Each level increase gold maximum and gold income by 10%. At level 4 new building is opened": "每级增加金币上限和金币收入10%。 在第 4 层，新建筑开放",
    "Increase your creatures resources gain by 20% at cost of 10% more energy consumed.": "以多消耗 10% 的能量为代价，将你的生物资源增益提高 20%。",
    "Maxed out": "已最大",
    "Motivation": "动机",
    "New home - new life": "新家——新生活",
    "per finished map": "每张完成的地图",
    "You get": "你会得到",
    "Both": "都显示",
    "Buttons": "按钮",
    "Confirmation Settings": "确认设置",
    "Input controls": "输入控制",
    "Notifications Settings": "通知设置",
    "Off": "关闭",
    "On": "打开",
    "Show confirmation when go negative balance after assign creature jobs": "分配生物工作后出现负余额时显示确认",
    "Show input on creature jobs page as": "在生物工作页面上显示输入为",
    "Show notification when battle lost": "战斗失败时显示通知",
    "Show notification when battle won": "战斗获胜时显示通知",
    "Show notification when building built": "建造时显示通知",
    "Show notification when creature dies": "生物死亡时显示通知",
    "Show notification when zone finished": "区域完成时显示通知",
    "Slider": "滑块",
    "of": "of",
    "Building queue:": "建筑队列：",
    "Each level add +1 building queue slot": "每级增加 +1 个建筑队列槽",
    "Increase your creatures resources gain by 20% at cost of 10% more energy consumed. Level 3 unlocks new research": "以多消耗 10% 的能量为代价，将你的生物资源增益提高 20%。 3级解锁新研究",
    "Learn basics of bargaining - improve your gold earned by 2 per work action": "学习讨价还价的基础知识 - 将您的金币提高 2 个工作动作",
    "Military": "军事",
    "Urbanism": "城市化",
    "Applied": "已应用",
    "Bank": "银行",
    "Development": "发展",
    "Each level increase banners gain on prestige by 10%": "每升一级，旗帜的威望提升 10%",
    "Each level increase gold maximum and gold income by another 10%": "每升一级，金币上限和金币收入再增加 10%",
    "Expand items": "展开物品",
    "Heirlooms": "传家宝",
    "Improves fighter stats by 46.00%": "提高战士属性 46.00%",
    "Inventory": "库存",
    "Items here have impact on game": "这里的物品对游戏有影响",
    "Items here persist through resets": "此处的物品通过重置保留",
    "Items here will be removed after you reset": "重置后此处的物品将被删除",
    "Monument of Yourself": "自己的纪念碑",
    "talisman of agression": "攻击护身符",
    "talisman of greediness": "贪婪护身符",
    "Provides you possibility to search for better battle-places. Each level increase territory gain by 20%": "为您提供寻找更好的战场的可能性。 每级增加20%的领地增益",
    "talisman of magic, expansion and energy": "魔法、扩张和能量护身符",
    "Revert changes": "还原更改",
    "Select item": "选择物品",
    "Sergeant": "军士",
    "Stored": "已存储",
    "Turn off auto purchase": "关闭自动购买",
    "Turn on auto purchase": "开启自动购买",
    "Watch tower": "瞭望塔",
    "You finished map 19. You recieved 7.02 territory.": "您完成了地图 19。您获得了 7.02 领土。",
    "talisman of soulharvest": "灵魂收割护身符",
    "Collapse items": "收起物品",
    "Drop item": "移除物品",
    "talisman of energy": "能量护身符",
    "You were about to portal back to you room in basement when you felt someones hand on your shoulder.": "当你感觉有人把手放在你的肩膀上时，你正要传送回地下室的房间。",
    "You: - Let's hope I won't die this time.": "你： - 希望这次我不会死。",
    "talisman of magic": "魔法护身符",
    "talisman of agression, expansion and saving": "侵略、扩张和存储护身符",
    "talisman of creation": "造物护身符",
    "talisman of saving": "存储护身符",
    "talisman of expansion": "扩张护身符",
    "Allows you building mega structures that persists through resets": "允许您建造通过重置持续存在的巨型结构",
    "Architecture": "建筑学",
    "Improves fighter stats by 50.00%": "提高战士属性 50.00%",
    "talisman of energy, creation and expansion": "能量、创造和扩张护身符",
    "Ore Mining": "矿石开采",
    "Unlock ore mining and refining. Each level improve mining efficiency by 10%": "解锁矿石开采和精炼。 每级提升挖矿效率10%",
    "Allows hiring blacksmiths and armorers. Each level increase their efficiency by 10%": "允许雇佣铁匠和军械师。 每个级别提高他们的效率10%",
    "Armorer": "装甲师",
    "Blacksmith": "铁匠",
    "Converts ore and wood to make tools.": "将矿石和木材转化为工具。",
    "Converts ore and wood to make weapons for your creatures.": "转换矿石和木材为你的生物制造武器。",
    "Each level decrease amount of souls required for creatures by 50%. Persists through resets.": "每升一级，生物所需的灵魂数量减少 50%。 通过重置持续存在。",
    "Each level increase your creatures attack by 10% (multiplicative), and unlock 5 additional zones at beginning of run. Persists through resets.": "每级增加你的生物攻击 10%（乘法），并在开始运行时解锁 5 个额外的区域。 通过重置持续存在。",
    "Each level increase your research by 25%. Persists through resets.": "每个级别都会使您的研究提高 25%。 通过重置持续存在。",
    "talisman of expansion and agression": "扩张和侵略护身符",
    "talisman of saving and energy": "存储护身符",
    "talisman of agression, magic, energy and soulharvest": "侵略、魔法、能量和灵魂收割护身符",
    "Forge": "锻造",
    "Improves fighter stats by 32.00%": "战士属性提高 32.00%",
    "Material": "材料",
    "Megastructure": "巨型结构",
    "Mine": "矿山",
    "Ore": "矿石",
    "Ore Miner": "矿工",
    "Provides metal ore.": "提供金属矿石。",
    "Pyramids": "金字塔",
    "talisman of creation, magic and soulharvest": "创造、魔法和灵魂收获的护身符",
    "talisman of energy, expansion and creation": "能量、扩张和创造的护身符",
    "The Great Library": "大图书馆",
    "Tools": "工具",
    "Unlock metal ore. Each level increase metal ore production by 10%": "解锁金属矿石。 每级增加金属矿石产量10%",
    "Weapons": "武器",
    "Zeus Statue": "宙斯雕像",
    "talisman of soulharvest, energy and expansion": "灵魂收割、能量和扩张的护身符",
    "Not assigned": "未分配",
    "Press key": "按键",
    "Provides raw material for building. Although it seems pretty cheap material, for some reason it's pretty hard to teach your creatures to cut wood": "为建筑提供原材料。 虽然它看起来很便宜，但由于某种原因，很难教你的生物砍木头",
    "Purchase time-management book to learn how to keep 2 actions auto-running": "购买时间管理书籍，了解如何让 2 个动作自动运行",
    "Show confirmation when go negative balance after assign skill efforts": "在分配技能努力后出现负余额时显示确认",
    "Show input on learning page as": "在学习页面上显示输入为",
    "Summon creatures": "召唤生物",
    "Summon max (x": "召唤最大值 (x",
    "Summon max creatures": "召唤最大生物",
    "Switch to actions tab": "切换到操作选项卡",
    "Switch to battle tab": "切换到战斗选项卡",
    "Switch to buildings tab": "切换到建筑物选项卡",
    "Switch to creatures tab": "切换到生物选项卡",
    "Switch to heirlooms tab": "切换到传家宝选项卡",
    "Switch to learning tab": "切换到学习选项卡",
    "Switch to research tab": "切换到研究选项卡",
    "Switch to settings tab": "切换到设置选项卡",
    "Switch to shop tab": "切换到商店选项卡",
    "Switch to story tab": "切换到故事选项卡",
    "talisman of aggression": "侵略的护身符",
    "Time": "时间",
    "talisman of resilience": "韧性护身符",
    "Mana efficiency": "法力效率",
    "Each level will boost your actions efficiency by increasing their output by 1%": "每个级别都会通过增加 1% 的输出来提高你的行动效率",
    "Each level will boost your actions efficiency by decreasing cooldowns by 1%": "每个级别都会通过减少 1% 的冷却时间来提高你的行动效率",
    "Each level increase your spells efficiency by 25%. After levels 5 and 10 unlock new researches": "每个级别都会使您的法术效率提高 25%。 5 级和 10 级后解锁新的研究",
    "Each level increase your actions efficiency by 20%. After level 10 unlock new powerful research.": "每个级别都会将您的动作效率提高 20%。 10级后解锁新的强大研究。",
    "Improves builders and building resources gatherers efficiency": "提高建设者和建筑资源收集者的效率",
    "By setting effort you are setting amount of energy you will spend per second to learn skill.": "通过设置努力，您可以设置每秒花费在学习技能上的能量。",
    "Purchase summoning efficiency book to decrease energy consumed by creatures by 0.5": "购买召唤效率书减少生物消耗的能量0.5",
    "Purchase summoning jobs knowledge book to increase job efficiency. +10% creature productions": "购买召唤职业知识书，提高工作效率。 +10% 生物产量",
    "Alchemy": "炼金术",
    "Auras": "光环",
    "Bosses": "老板",
    "Combat Reflexes": "战斗反射",
    "Each level increase banners gain on prestige by 10%. This effect is multiplied by your total fame amount.": "每升一级，旗帜获得的威望提高 10%。这个效果乘以你的总声望值。",
    "Each level increase your creatures base precision by 5 and evasion by 4": "每升一级，你的生物基础精度提高 5 点，闪避提高 4 点",
    "Efficiency:": "效率：",
    "Empowered": "授权",
    "Epic": "史诗",
    "Fighting skills": "格斗技巧",
    "Improves fighter accuracy and evasion by 23.00%": "将战斗机的准确度和闪避提高 23.00%",
    "Improves fighter attack and HP by 46.00%": "提高战士攻击力和生命值 46.00%",
    "Increase fighting loot by 25%. Level 5 unlocks new research": "战斗战利品增加 25%。 5级解锁新研究",
    "Increase your creatures evasion and accuracy by 25%. After level 10 unlocks new research.": "将你的生物的闪避和准确度提高 25%。 10级后解锁新的研究。",
    "Learn how to move large things with power of mind. Unlocks new megastructures. Each level decrease building time by 5%": "学习如何用心灵的力量移动大的东西。解锁新的巨型结构。每级减少 5% 的建造时间",
    "Levitation": "悬浮",
    "Map": "地图",
    "New training techniques for your warriors allows to increase their vitality. +1 base HP to your creatures per level. (multiplied by other bonuses)": "为您的战士提供的新训练技术可以增加他们的活力。每级 +1 基础生命值给你的生物。 （乘以其他奖励）",
    "Purchase book learn your creatures to be 50% more precise": "购买书让你的生物更精确 50%",
    "Rare": "稀有的",
    "Resilience": "弹力",
    "Set minimum tier drop filter": "设置最低层下降过滤器",
    "Trainer": "培训师",
    "Training Center": "培训中心",
    "Unlock alchemists job. Can convert your flasks to something more efficient. Each level improves alchemist efficiency by 10%": "解锁炼金术士的工作。可以将您的烧瓶转换为更有效的东西。每级提高炼金术士效率10%",
    "Unlock new way of your power improvement - auras. Can be find in maps. Each level add new active aura slot": "解锁提升力量的新方式 - 光环。可以在地图中找到。每个级别都会添加新的主动光环槽",
    "Unlocks fighting. Each level increase your creatures HP and attack by 25%. Levels 3 and 6 unlock new researches": "解锁战斗。每一级都会增加你的生物生命值和攻击力 25%。 3 级和 6 级解锁新研究",
    "Unlocks hiring sergeant and trainer. Each level increase sergeant and trainer bonus by 10%. Level 3 unlocks new research.": "解锁雇佣军士和训练师。每级增加 10% 的中士和训练师奖励。 3 级解锁新的研究。",
    "Your fighters are healing": "你的战士正在康复",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Heirlooms are given when you win battles.  To make an heirloom bonus active, select it by clicking on it (once selected it will have a purple border) then click on one of the 'Applied' slots. If the slot you try to put the item in already has an item item in it, the item inside the slot will be moved to the inventory": "当你赢得战斗时会获得传家宝。 要激活传家宝奖励，请通过单击将其选中（一旦选中，它将具有紫色边框），然后单击“已应用”插槽之一。 如果您尝试放置物品的插槽中已经有物品物品，则该插槽内的物品将被移动到库存中",
    "Heirlooms are given when you win battles. To make heirloom bonuses active select it (by clicking on it, once it selected it's surrounded by purple border) and than click on one of \"Applied\" slots. If slot is where you try to put item is not empty, item inside it will be moved to inventory.": "当您赢得战斗时会获得传家宝。 要激活传家宝奖励，请选择它（通过单击它，一旦选择它就会被紫色边框包围），然后单击“应用”插槽之一。 如果您尝试放置物品的插槽不是空的，则其中的物品将被移动到库存中。",
    "You progress over map each time you win a battle. Each won battle provides you some souls (Higher map level - greater amount). Once you clear cell 100 you finish map, and provided some territory (Amount depends on map level also). If you turn off auto toggle next map, you will restart your current map.": "每次赢得战斗时，您都会在地图上前进。 每次获胜的战斗都会为您提供一些灵魂（更高的地图级别 - 更多的数量）。 清除单元格 100 后，您就完成了地图，并提供了一些领土（数量也取决于地图级别）。 如果您关闭自动切换下一张地图，您将重新启动当前地图。",
    "Each banner type has several tiers. Each tier after first multiplies effect of previous one. By converting all your banners to higher tier you will loose all previous tier banners. For example, converting 2nd tier to 3rd will remove 2nd tier banners, add 5 times smaller amount to 3rd tier. Other tiers will keep the same.": "每种旗帜类型都有几个层次。 第一层之后的每一层都将前一层的效果相乘。 通过将所有旗帜转换为更高级别，您将失去所有先前级别的旗帜。 例如，将 2nd 层转换为 3rd 将删除 2nd 层旗帜，将 5 倍的数量减少到 3rd 层。 其他等级将保持不变。",
    "Dulequar gave you some scroll and disappeared. Well, another adventure ends up with some weird book or scroll you need to learn. \n        You unfolded the scroll and read spell written on it out loud. But nothing happened. Well, maybe you should make your researchers\n         to focus on investigating it.": "Dulequar 给了你一些卷轴然后消失了。 好吧，另一个冒险最终会得到一些你需要学习的奇怪的书或卷轴。 \n你展开卷轴，大声读出上面写的咒语。 但是什么也没发生。 好吧，也许你应该让你的研究人员\n 专注于研究它。",
    "You squeezed Dulequar's hand, and started feeling strange vibrations. Everything darkened for a few moments. After\n        you opened your eyes you realized yourself in ruined city. Everything is burning. You hear a lot of people screaming\n         around.": "你捏了捏 Dulequar 的手，开始感觉到奇怪的震动。 一切都变暗了片刻。 当你睁开眼睛后，你意识到自己身处废墟城市。 一切都在燃烧。 你听到很多人在周围尖叫\n。",
    "Dulequar: - You can't leave in magic shop basements forever. You proved yourself in many battles. Each peace of land \n        cleared out from Azragard troops becomes yours. So, you can use it to make yourself even stronger and better prepared \n        for our Holy war. Let's don't waste too much time here.": "Dulequar： - 你不能永远留在魔法商店的地下室。 你在许多战斗中证明了自己。 从阿兹拉加德军队中清除的每一块土地都将成为你的。 所以，你可以用它来让自己变得更强大，更好地为我们的圣战做好准备\n。 我们不要在这里浪费太多时间。",
    "Dulequar smiled and stretched his hand. Another weird traveling. You opened you eyes and recognized yourself surrounded \n        by gorgeous palaces and temples. Hundreds of troles, ogres and other strange creatures around doing their business.": "Dulequar 微笑着伸出了手。 另一个奇怪的旅行。 你睁开眼睛，发现自己被华丽的宫殿和寺庙所包围。 数以百计的巨魔、食人魔和其他奇怪的生物在他们周围做生意。",
    "Version history": "版本历史",
    "Dulequar: -- You lost everything but in exchange you received something priceless - knowledge and blessing from the skies.\n        You have proven your perseverance and endurance. In exchange you received new powers. Don't worry, each next try \n        you will become more and more powerful. This is the way I have passed once upon a time.": "Dulequar: -- 你失去了一切，但换来的是无价之宝——来自天空的知识和祝福。\n你已经证明了你的毅力和耐力。 作为交换，你获得了新的权力。 别担心，下次尝试\n你会变得越来越强大。 这就是我曾经走过的路。",
    "Each banner type have several tiers. Each tier after first multiplies effect of previous one. By converting to higher tier you will loose all previous tier banners. For example, converting 2-nd tier to 3-rd will remove 2-nd tier banners, add 5 times smaller amount to 3-rd tier. Other tiers will keep the same.": "每种旗帜类型都有几个层次。 第一层之后的每一层都将前一层的效果相乘。 通过转换为更高级别，您将失去所有先前级别的旗帜。 例如，将 2-nd 层转换为 3-rd 将删除 2-nd 层旗帜，将 5 倍的数量减少到 3-rd 层。 其他等级将保持不变。",
    "You summoned another creature and felt completely exhausted. Again, strange memories covered you. You laying at the ground\n         blinded by bright light. As the light started fainting you see four strange mirrors with differently colored... portals\n         inside them?": "你召唤了另一个生物并感到完全筋疲力尽。 又一次，奇怪的记忆笼罩着你。 你躺在地上\n 被强光弄瞎了。 当光线开始减弱时，您会看到四面奇怪的镜子，里面有不同颜色的……传送门\n？",
    "NOTE FROM DEV: You can choose any banner you want. I'd suggest choosing green one for first prestige, since it dramatically decreases time you need to pass first steps of new run. You will loose all your skills, creatures and resources but will be given boost depending on banner type": "来自开发人员的注意事项：您可以选择任何您想要的旗帜。 我建议选择绿色作为第一个声望，因为它大大减少了您通过新运行的第一步所需的时间。 您将失去所有技能、生物和资源，但会根据旗帜类型获得提升",
    "Strange man in cloak: -- The one who is searching will always find. There are way much more books at shop. I haven't \n        seen you there for a while. When I was as young and inexperienced as you I spent whole days studying. You should learn more.\n        I'd suggest you starting with alchemy and improve your summoning skills. Trust me, you'll need them in future so much.": "斗篷怪人：——寻找的人总能找到。 商店里的书要多得多。 我已经有一段时间没有看到你了。 当我像你一样年轻和缺乏经验时，我整天都在学习。 你应该学习更多。\n我建议你从炼金术开始，提高你的召唤技能。 相信我，你将来会非常需要它们。",
    "Strange man in cloak performed some strange spell and turned dead rat on the floor into table full of delicious \n        cookies and fruits. You reached out to the grapes, but strange wizard spelled another strange combination of words,\n        and it turned into red hot coals. You screamed out from pain and throw it on the ground. Coals hit the floor, and\n        turned back into dead rat. You starring at the wizard in surprise": "披着斗篷的怪人施展了一些奇怪的咒语，把地板上的死老鼠变成了一桌美味的\n饼干和水果。 你伸手去拿葡萄，但奇怪的巫师拼出了另一个奇怪的单词组合，\n然后它变成了炽热的煤炭。 你痛苦地尖叫起来，把它扔在地上。 煤块掉到地板上，\n 又变成了死老鼠。 你惊讶地盯着巫师",
    "You sit down reading new herbalism book. You kinda bored turning page by page, hardly understanding\n    why you might need this all knowledge. And finally you found something - a recipe for some flask that should\n    make your minions more powerful. Yeah, that's indeed what you need": "你坐下来阅读新的草药学书。 你一页一页地翻页有点无聊，几乎不明白\n为什么你可能需要这些知识。 最后你找到了一些东西——一个烧瓶的配方，它可以\n让你的爪牙更强大。 是的，这确实是你需要的",
    "You keep reading book, full of enthusiasm. You performed some rituals, got some success. Your magic stamp\n            started glowing. According to book, now you can perform some ritual to summon some weird creatures.\n        What? You can summon some demons? Other mages? You definitely have to try it out!": "你继续看书，充满热情。 你做了一些仪式，取得了一些成功。 你的魔法印章\n开始发光。 根据书本，现在你可以进行一些仪式来召唤一些奇怪的生物。\n 什么？ 你可以召唤一些恶魔？ 其他法师？ 你一定要试试看！",
    "You followed salesman. After couple minutes walking through dark and wet cellar corridors a small door opened in front of you.\n        You see small room. Unbearable smell and dead rats surround you. You glanced at small bed in the corner.": "你跟着推销员。 在穿过黑暗潮湿的地窖走廊几分钟后，一扇小门在你面前打开了。\n 你看到了小房间。 难以忍受的气味和死老鼠围绕着你。 你瞥了一眼角落里的小床。",
    "You caught displeased look of salesman, but you don't care. You feel like you'd better stay at rancho. But, again,\n        you can become a mage! You set on bad and opened book. Full of mysterious rituals and spells. But ok, let's start from beginning.\n        You saw some strange rithual called \"Souls gathering\". You definitely want to try it.": "你看到了推销员不悦的眼神，但你不在乎。 你觉得你最好留在牧场。 但是，再次，\n你可以成为一名法师！ 你开始坏了，打开了书。 充满神秘的仪式和咒语。 但是，好吧，让我们从头开始。\n 你看到了一些奇怪的仪式，叫做“灵魂聚集”。 你肯定想试试。",
    "After trying to cast another spell, you got stricken by bright light. After couple seconds it disappeared and you see\n            nothing but small crooked skeleton. Well, not bad for first time. You tried to talk to your new creature - but nothing.\n            You feel you started getting more and more tired. Seems like this creature uses your energy to exist.": "在尝试施展另一个法术后，你被强光击中。 几秒钟后，它消失了，你只看到一个弯曲的小骷髅。 嗯，第一次还不错。 你试着和你的新生物说话——但什么也没有。\n你觉得你开始越来越累了。 看起来这个生物是利用你的能量存在的。",
    "Another week passed. You almost lost sense of time devoting all of you to work and training. Finally,\n            you feel yourself ready. You entered weird shop again, and purchased Magic Stamp. It looks like \n            regular one, by the way. Only difference is some strange symbols written on it. You standing at the shop\n            looking at your new purchase barely understanding why you are doing all this stuff.": "又一个星期过去了。 你几乎失去了把时间花在工作和培训上的感觉。 最后，\n 你觉得自己准备好了。 你又进了奇怪的商店，购买了魔法印章。 顺便说一句，它看起来像 \n 普通的。 唯一不同的是上面写着一些奇怪的符号。 你站在商店\n 看着你的新购买几乎不明白你为什么要做这些事情。",
    "Salesman: -- What? You still haven't it? That's unacceptable! You can do almost nothing without it. Well, I think I have one for you.\n                    But, it's not cheap. Once you purchase it I can help you improving your skills. Otherwise I can do nothing.": "售货员：——什么？ 你还没有吗？ 这是不可接受的！ 没有它，你几乎什么都做不了。 好吧，我想我有一个给你。\n 但是，它并不便宜。 一旦你购买它，我可以帮助你提高你的技能。 否则我什么也做不了。",
    "You spent couple weeks practicing and training. You almost get used to morning meditation rituals. \n            The only issue that makes you worried is that rancho owner started suspecting that something is \n            wrong with you.": "你花了几个星期练习和训练。 你几乎习惯了早晨的冥想仪式。 \n 唯一让你担心的问题是牧场主开始怀疑你有问题\n。",
    "After trying to cast another bunch of spells you realized that you get a little bored. There should be more use\n        for magic isn't it? You decided to walk to same shop where you purchased book. You opened old creaking doors and entered shop. \n         You saw familiar slightly smiling face of salesman.": "在尝试施放另一组咒语后，您意识到自己有点无聊。 魔术应该有更多用途，不是吗？ 你决定走到你买书的同一家商店。 你打开吱吱作响的旧门，走进商店。 \n 你看到了推销员熟悉的略带微笑的脸。",
    "Man gave you piece of paper and disappeared... You started thinking that you gone crazy. But wait, you still standing\n        on the crossroad, keeping piece of paper. You unfolded it and saw something looking like price tag - \"40 gold\", with address\n        written above. Well, you feel at least it worth a try, even if you faced just another swindler": "男人给了你一张纸然后消失了……你开始以为你疯了。 但是等等，你仍然站在十字路口，拿着一张纸。 你打开它，看到一个看起来像价格标签的东西——“40 金币”，上面写着地址\n。 嗯，你觉得至少值得一试，即使你面对的是另一个骗子",
    "Again silence. Eyes of person started glowing brighter. You started seeing a lot of dark silhouettes behind\n        a person. More and more of them. You started to walk back slowly. Finally one of silhouettes sticks a knife into\n        persons neck! A mysterious person falls and says in a hoarse voice - \"I should have been more careful\"\n        You screaming out: \"WHAT ARE YOU DOING?! HOLD THE MURDER!\"": "再次沉默。 人的眼睛开始发光。 你开始在一个人的身后看到很多黑暗的剪影。 他们越来越多。 你开始慢慢往回走。 最后一个人影把刀插进了\n人的脖子！ 一个神秘的人摔倒了，用嘶哑的声音说——“我应该更小心点”\n你尖叫道：“你在做什么？！抓住谋杀！”",
    "Physical training will give you some passive energy regeneration. After performing it couple times you can set itto automation and take some coffee, or keep clicking rest if you want things to go faster. Also, shop can have some helpfull items for you": "体育锻炼会给你一些被动的能量再生。 执行几次后，您可以将其设置为自动化并喝杯咖啡，或者如果您想让事情进展得更快，请继续点击休息。 此外，商店可以为您提供一些有用的物品",
    "You realized yourself laying on the floor once more, screaming. You hear the voice: \"You should take some rest.\" \n        You opened your eyes and see just rancho owner staying above you. You feel like you gone crazy, but than another feeling \n        overwhelms you - you should work hard. You should become better, stronger...": "你意识到自己再次躺在地板上，尖叫着。 你听到声音：“你应该休息一下。” \n 你睁开眼睛，看到只是牧场主站在你的上方。 你觉得自己疯了，但比另一种感觉 \n 压倒你 - 你应该努力工作。 你应该变得更好，更强...",
    "Wait! You didn't saw it was written here at the shop. Large mirror occurred in front of you. You see in the mirror\n        some strange person under black cloak. You asking quietly: \"Who are you?\". You got nothing but silence as an answer.\n        \"Who are you\" - you screamed out loudly.": "等等！ 你没有看到它是在商店里写的。 大镜子出现在你面前。 你在镜子里看到\n 一个穿着黑色斗篷的奇怪人。 你轻声问：“你是谁？”。 你得到的只有沉默作为答案。\n“你是谁”——你大声尖叫。",
    "You understand that you won't survive long in these cold and wet woods. After spending couple hours traveling you saw some settlement.\n             It appears much smaller than you thought at first glance, however it still appears to have a market filled with fresh meat, fish and vegetables. \n             Your stomach growls painfully, but you're broke!": "你知道你在这些又冷又湿的树林里活不了多久。 花了几个小时旅行后，您看到了一些定居点。\n 乍一看，它似乎比您想象的要小得多，但它似乎仍然有一个充满新鲜肉类、鱼类和蔬菜的市场。 \n你的肚子疼得咕咕叫，但你已经破产了！",
    "You realized yourself again laying on the floor. Several people standing around you annoying you with questions if you are\n        alright. You don't want to talk to them. You want just purchase this useless empty book and run away. You feel so helpless, \n        for no obvious reason for it.": "你意识到自己再次躺在地板上。 如果你没事的话，站在你周围的几个人会用问题来烦你。 你不想和他们说话。 你只想买这本没用的空书然后跑掉。 你感到很无助，\n没有明显的原因。",
    "While bargaging with one of local traders he suggested that you could work at his brothers ranch a small ways away from the settlement. \n        Salary isn't much but it'll get you a meal. Seeing your hunger, the trader gave you a baked chicken leg for free. \n        You ate it and began your trek towards the ranch stable.": "在与一位当地商人讨价还价时，他建议你可以在离定居点不远的他兄弟的牧场工作。 \n 薪水不多，但可以给你吃顿饭。 商人见你饿了，免费送你一只烤鸡腿。 \n 你吃了它，开始向牧场马厩跋涉。",
    "Rainy Saturday morning, you walking across market streets. Suddenly you noticed some accessories shop. You stepped \n        into. The eyes widen from the variety of all sorts of little and useless things. But, you found some book on one of\n        hundreds shelves. It seems empty, but...": "周六早上下雨，你穿过市场街道。 突然你注意到一些饰品店。 你踏入了\n。 各种各样的琐碎无用的东西睁大了眼睛。 但是，您在\n 数百个书架中的一个上发现了一些书。 好像是空的，但是...",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "v0.0.3": "v0.0.3",
    "s": "s",
    "[": "[",
    "]": "]",
    "/": "/",
    "+": "+",
    "VS": "VS",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单选项卡模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Income: ": "收益: ",
    "Advanced magic ": "进阶魔法 ",
    "Bones masterity ": "骨骼精通 ",
    "You lost the battle at ": "你输掉了战斗在 ",
    "Normal  ": "普通的",
    "Rare  ": "稀有的",
    "Epic  ": "史诗的",
    "Empowered  ": "赋能的",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " / s": " / 秒",
    " energy/sec": " 能量/秒",
    " max energy": " 最大能量",
    " max gold": " 最大黄金",
    " max mana": "最大法力",
    " boost": " 提升",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^你在(.+)$/,
    /^收益(.+)$/,
    /^你输(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^X([\d\.]+)K$/,
    /^([\d\.]+)K$/,
    /^\-([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^\+([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+)T$/,
    /^([\d\.]+)Qa$/,
    /^([\d\.]+)Qi$/,
    /^([\d\.]+)Sx$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^X([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You won the battle at (.+). You recieved (.+) souls.$/, '你在 $1 赢得了战斗。 你收到了 $2 灵魂。'],
    [/^(.+) to building resources capacity$/, '$1 到建筑资源容量'],
    [/^You won the battle at (.+). You received (.+) souls.$/, '你在 $1 赢得了战斗。 你收到了 $2 灵魂。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You finished map (.+). You recieved (.+) territory.$/, '您完成了地图 $1。您获得了 $2 领土。'],
    [/^You finished map (.+). You received (.+) territory.$/, '您完成了地图 $1。您获得了 $2 领土。'],
    [/^Start with (.+) more maximum energy and (.+) energy regeneration$/, '开始时增加 $1 点最大能量和 $2 能量恢复'],
    [/^Start with (.+) more maximum gold and more passive gold income (.+). After level (.+) unlock new research$/, '从 $1 更多的最大金币和更多的被动金币收入 $2 开始。 $3 级后解锁新研究'],
    [/^Start with (.+) more maximum energy and (.+) energy regeneration$/, '开始时增加 $1 点能量上限和 $2 能量恢复'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^\+([\d\.]+)\% to building speed$/, '\+$1\% 建造速度'],
	[/^\+([\d\.]+)\% to souls gained$/, '\+$1\% 灵魂增益'],
	[/^\+([\d\.]+)\% to gold maximum$/, '\+$1\% 黄金上限'],
	[/^\+([\d\.]+)\% to creatures HP$/, '\+$1\% 生物生命值'],
	[/^\+([\d\.]+)\% to gold income$/, '\+$1\% 黄金收入'],
	[/^\+([\d\.]+)\% to territory gain$/, '\+$1\% 领地增益'],
	[/^\+([\d\.]+)\% to maximum energy$/, '\+$1\% 能量上限'],
	[/^\+([\d\.]+)\% to maximum mana$/, '\+$1\% 法力上限'],
	[/^\+([\d\.]+)\% to creatures attack$/, '\+$1\% 对生物攻击'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);